### ISSUE TITLE
Consulta esta funcionando la libreria?

### ISSUE THREAD

**Issue by leonciokof** [pedroburon/tbk#17]
He intentado probar la libreria usando el ejemplo del README y cambiando request_ip por mi ip publica y usando commerce test=True pero siempre transbank luego de confirmar el pago me redirecciona a la url success_url sin responder antes a la url de confirmation_url.

**Comment by farodrig** [comment]
En mi caso, siempre me redirecciona a la url failure_url sin ir a la confirmation_url. Lograste descubrir el porque?

**Comment by leonciokof** [comment]
También me paso lo mismo, estoy esperando que responda @pedroburon

**Comment by pedroburon** [comment]
Hola! Por lo que me puedo imaginar, transbank no está realizando el post al confirmation_url porque no pudo llegar. El request ip no es el ip de la máquina donde está el servicio, si no que del pagador. El confirmation_url debe tener la ip pública de la máquina donde está el servicio. Voy a aclarar esto en el README.

Disculpen la demora y espero les sirva la respuesta.

Saludos!

**Comment by farodrig** [comment]
Justamente el problema, al menos en mi caso era que el confirmation_url debía ser la ip pública de la máquina. El request_ip sirve para algo??, no logro darme cuenta en q parte del código se utiliza realmente.

**Comment by pedroburon** [comment]
El `request_ip` lo pide el servidor de transbank para crear el token, en realidad no se si ellos lo utilicen pero sé que se usa en el log en https://github.com/pedroburon/tbk/blob/master/tbk/webpay/logging/official.py#L63-L78.

@farodrig lograste entonces que funcionara? Me podrías contar con qué tecnologías lo estás utilizando?

Saludos!

**Comment by farodrig** [comment]
Finalmente, logré q funcionara poniendo en confirmation_url la ip pública de la máquina, todo esto con testing=True. Estoy utilizandolo en un carro de compra implementado con django.
Para que funcionara el log, tuve q modificar una parte del código, ya que TBK_VCI me aparecía como nulo y se caia, asi q hice q en el caso q fuera nulo, se le asignara un valor por defecto. Algo similar se hace en https://github.com/sagmor/tbk/blob/master/lib/tbk/webpay/logger/official_logger.rb#L61-L62

**Comment by pedroburon** [comment]
Excelente, podrías hacer un pull request con las modificaciones?

Saludos.
