### ISSUE TITLE
Prueba en flask

### ISSUE THREAD

**Issue by leonciokof** [pedroburon/tbk#19]
Tengo el siguiente codigo pero no logro que funcione.

https://gist.github.com/leonciokof/c6c6a57de80610741f91

Siempre luego de ingresar el medio de pago aparece esto:

http://i.imgur.com/iLsgm1X.png

@pedroburon o @farodrig que estoy haciendo mal?

**Comment by pedroburon** [comment]
Te pasa esto antes de ingresar los datos de la tarjeta? La verdad es que nunca he probado utilizando success_url en localhost, quizás sea eso en caso de que no haya pasado por la página de confirmación.

**Comment by leonciokof** [comment]
Me pasa al final del proceso. Es decir ingreso la tarjeta, rut y clave.

**Comment by pedroburon** [comment]
Y se genera la petición a tu servidor? Es posible acceder a la IP que le
mandas desde fuera de tu red?

**Comment by leonciokof** [comment]
Es posible acceder a la ip desde el exterior. Y nunca llega la petición
post de confirmación.

**Comment by pedroburon** [comment]
Puede ser también que no acepte webpay confirmar en ese puerto, intenta con el puerto 8080 para descartar que sea eso.

**Comment by leonciokof** [comment]
Hice la prueba en el puerto 8080 y pasa lo mismo. Acá la modificación https://gist.github.com/leonciokof/c6c6a57de80610741f91

Es posible que alguno comparta algún código para ver en que estoy mal?

**Comment by pedroburon** [comment]
@leonciokof instalé tu app en un servidor con IP fija y no me funcionó en el puerto 8080 pero si en el puerto 80. Tuve que modificar algunas partes del código para que funcionara. Te dejo el gist con los cambios: https://gist.github.com/pedroburon/f8de2e1dc9e8b8edb617

**Comment by leonciokof** [comment]
Por fin lo pude hacer funcionar, muchas gracias por la ayuda. Apenas pueda creo un repositorio con el código y las dependencias, si te interesa puedes incluirlo como proyecto de ejemplo.

**Comment by pedroburon** [comment]
Sería excelente! Cuéntame cómo te va con la certificación.

Saludos!

**Comment by leonciokof** [comment]
La certificación la hice hace tiempo, llamando los cgi desde python. Hice lo mismo en node hace tiempo. Actualmente me encuentro portando tu librería a node (un tanto lento). El port a node esta acá https://github.com/leonciokof/tbk y el proyecto de ejemplo en flask esta acá https://github.com/leonciokof/flask-tbk. Saludos

**Comment by pedroburon** [comment]
Que bueno, la única acotación que haría es que uses la librería de python dotenv en vez de python-dotenv :stuck_out_tongue_winking_eye:  https://github.com/pedroburon/dotenv
